spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000 # 连接超时时间
      maximum-pool-size: 10 # 最大连接数
      minimum-idle: 5 # 最小空闲连接数
      idle-timeout: 600000 # 空闲连接超时时间
      max-lifetime: 1800000 # 连接最大存活时间

      jpa:
        open-in-view: false
        show-sql: true
        properties:
          hibernate:
            format_sql: true
            jdbc:
              batch_size: 50
              order_inserts: true
              order_updates: true
            query:
              plan_cache_max_size: 2048
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
          ddl-auto: validate
